platform :ios, "7.0"

pod 'RestKit'
pod 'ViewDeck', '=2.2.11'
pod 'Reachability'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'GoogleAnalytics-iOS-SDK'
pod 'TTTAttributedLabel'
pod 'hpple'
pod 'MHVideoPhotoGallery'
pod 'TSMessages'
pod 'MGSwipeTabBarController', '=2.0'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'DKToolbar', '=0.0.8'
pod 'TGCameraViewController', '=1.2'
pod 'Colours'
pod 'MZFormSheetController'
pod 'Masonry'
